type User {
  id: ID!
  username: String!
  password: String!

  firstname: String!
  lastname: String!

  email: String!
  birthdate: String

  isActive: Boolean!
  isAdmin: Boolean!

  created: String!
  modified: String!
}

type UserPayload {
  success: Boolean!
  message: String!
  payload: User!
}

type Query {
  dummy: String!
  getUsers: [User]!
}

type Mutation {
  # TODO: Returns specific data, not only a string.address
  register(username: String, email: String, password: String): UserPayload!
}
